import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Download, Copy, Check } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { listTopics } from "@/lib/mcp";
import { useConnectionStore } from "@/store/connection";

function generateToml(serverUrl: string, topics: { id: string; label: string; description: string; tags: string[]; url?: string }[]): string {
  const host = (() => {
    try {
      const u = new URL(serverUrl);
      return u.hostname;
    } catch { return "127.0.0.1"; }
  })();
  const port = (() => {
    try {
      return new URL(serverUrl).port || "3000";
    } catch { return "3000"; }
  })();

  const feedsToml = topics.map((t) => [
    `[[connector.feeds]]`,
    `topic_id          = "${t.id}"`,
    `topic_label       = "${t.label}"`,
    `topic_description = "${t.description}"`,
    `topic_tags        = [${t.tags.map((tag) => `"${tag}"`).join(", ")}]`,
    `url               = "${t.url ?? `https://example.com/${t.id}/feed.xml`}"`,
  ].join("\n")).join("\n\n");

  return `# ferrisletter.toml — generated by Ferrisletter Admin
# Edit and run: ferrisletter-server --config ferrisletter.toml

[transport]
mode = "sse"
host = "${host}"
port = ${port}

[connector]
type = "rss"

${feedsToml}
`.trimStart();
}

export function Export() {
  const { serverUrl } = useConnectionStore();
  const [copied, setCopied] = useState(false);

  const topicsQuery = useQuery({ queryKey: ["topics"], queryFn: listTopics });
  const topics = topicsQuery.data ?? [];
  const toml = generateToml(serverUrl, topics);

  async function copyToml() {
    try {
      await navigator.clipboard.writeText(toml);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy — try selecting the text manually");
    }
  }

  function downloadToml() {
    const blob = new Blob([toml], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ferrisletter.toml";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded ferrisletter.toml");
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-lg font-semibold text-[var(--color-text)]">Export Config</h1>
        <p className="text-sm text-[var(--color-text-muted)]">
          Download your current server configuration as{" "}
          <code className="font-mono text-xs text-[var(--color-accent)]">
            ferrisletter.toml
          </code>
        </p>
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>ferrisletter.toml</CardTitle>
              <CardDescription>
                Generated from {topics.length} topic{topics.length !== 1 ? "s" : ""} · RSS connector
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={copyToml}>
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button size="sm" onClick={downloadToml}>
                <Download size={13} />
                Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-0">
          <pre className="overflow-x-auto rounded-lg bg-[var(--color-surface)] border border-[var(--color-border)] p-4 text-xs font-mono text-[var(--color-text-muted)] leading-relaxed whitespace-pre">
            {topicsQuery.isLoading ? "Loading…" : toml}
          </pre>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Usage</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-[var(--color-text-muted)]">
          <div>
            <p className="font-medium text-[var(--color-text)] mb-1">Run with config file</p>
            <code className="block font-mono text-xs bg-[var(--color-surface)] border border-[var(--color-border)] rounded px-3 py-2 text-[var(--color-accent)]">
              ferrisletter-server --config ferrisletter.toml
            </code>
          </div>
          <div>
            <p className="font-medium text-[var(--color-text)] mb-1">Or via environment variable</p>
            <code className="block font-mono text-xs bg-[var(--color-surface)] border border-[var(--color-border)] rounded px-3 py-2 text-[var(--color-accent)]">
              FERRISLETTER_CONFIG=/path/to/ferrisletter.toml ferrisletter-server
            </code>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
