import { useState, useEffect } from "react";
import { Download, Copy, Check, AlertCircle, Zap } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useConnectionStore } from "@/store/connection";
import { useDraftStore } from "@/store/draft";
import { apiExportConfig, apiHealthCheck } from "@/lib/api";

function generateToml(
  serverUrl: string,
  feeds: { topic_id: string; url: string }[],
  topics: { id: string; label: string; description: string; tags: string[] }[],
): string {
  const host = (() => {
    try { return new URL(serverUrl).hostname; } catch { return "127.0.0.1"; }
  })();
  const port = (() => {
    try { return new URL(serverUrl).port || "3000"; } catch { return "3000"; }
  })();

  const feedsToml = feeds.map((f) => {
    const topic = topics.find((t) => t.id === f.topic_id);
    if (!topic) return null;
    return [
      `[[connector.feeds]]`,
      `topic_id          = "${topic.id}"`,
      `topic_label       = "${topic.label}"`,
      `topic_description = "${topic.description}"`,
      `topic_tags        = [${topic.tags.map((tag) => `"${tag}"`).join(", ")}]`,
      `url               = "${f.url}"`,
    ].join("\n");
  }).filter(Boolean).join("\n\n");

  return `# ferrisletter.toml — generated by Ferrisletter Admin
# Edit and run: ferrisletter-server --config ferrisletter.toml

[transport]
mode = "sse"
host = "${host}"
port = ${port}

[connector]
type = "rss"

${feedsToml || "# No feeds configured yet — add feeds in the Connectors page"}
`.trimStart();
}

export function Export() {
  const { serverUrl, apiKey } = useConnectionStore();
  const { topics, feeds, isDirty } = useDraftStore();
  const [copied, setCopied] = useState(false);
  const [apiAvailable, setApiAvailable] = useState(false);
  const [liveToml, setLiveToml] = useState<string | null>(null);

  useEffect(() => {
    if (apiKey) {
      apiHealthCheck(apiKey).then((ok) => {
        setApiAvailable(ok);
        if (ok) {
          apiExportConfig(apiKey).then(setLiveToml).catch(() => null);
        }
      });
    } else {
      setApiAvailable(false);
      setLiveToml(null);
    }
  }, [apiKey]);

  const toml = liveToml ?? generateToml(serverUrl, feeds, topics);

  async function copyToml() {
    try {
      await navigator.clipboard.writeText(toml);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Could not copy — try selecting the text manually");
    }
  }

  function downloadToml() {
    const blob = new Blob([toml], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ferrisletter.toml";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded ferrisletter.toml");
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-lg font-semibold text-[var(--color-text)]">Export Config</h1>
        <p className="text-sm text-[var(--color-text-muted)]">
          Download your current server configuration as{" "}
          <code className="font-mono text-xs text-[var(--color-accent)]">
            ferrisletter.toml
          </code>
        </p>
      </div>

      {isDirty && (
        <div className="flex items-center gap-2 rounded-lg border border-[var(--color-accent)]/30 bg-[var(--color-accent-subtle)] px-4 py-2.5 text-sm text-[var(--color-accent)]">
          <AlertCircle size={14} className="shrink-0" />
          You have unsaved draft changes — download the config to apply them.
        </div>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                ferrisletter.toml
                {apiAvailable && (
                  <span className="flex items-center gap-1 text-xs font-normal text-emerald-400">
                    <Zap size={11} />
                    Live from server
                  </span>
                )}
              </CardTitle>
              <CardDescription>
                {feeds.length} feed{feeds.length !== 1 ? "s" : ""} · {topics.length} topic{topics.length !== 1 ? "s" : ""} · RSS connector
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={copyToml}>
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button size="sm" onClick={downloadToml}>
                <Download size={13} />
                Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-0">
          <pre className="overflow-x-auto rounded-lg bg-[var(--color-surface)] border border-[var(--color-border)] p-4 text-xs font-mono text-[var(--color-text-muted)] leading-relaxed whitespace-pre">
            {toml}
          </pre>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Usage</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-[var(--color-text-muted)]">
          <div>
            <p className="font-medium text-[var(--color-text)] mb-1">Run with config file</p>
            <code className="block font-mono text-xs bg-[var(--color-surface)] border border-[var(--color-border)] rounded px-3 py-2 text-[var(--color-accent)]">
              ferrisletter-server --config ferrisletter.toml
            </code>
          </div>
          <div>
            <p className="font-medium text-[var(--color-text)] mb-1">Or via environment variable</p>
            <code className="block font-mono text-xs bg-[var(--color-surface)] border border-[var(--color-border)] rounded px-3 py-2 text-[var(--color-accent)]">
              FERRISLETTER_CONFIG=/path/to/ferrisletter.toml ferrisletter-server
            </code>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
